export LD_PRELOAD=./libsocket_retarder.so
export SOCKET_RETARDER_DEBUG=2
export SOCKET_RETARDER_DNS=0
export SOCKET_RETARDER_DISTRIBUTION=uniform
export SOCKET_RETARDER_UNIFORMDIST_A=250
export SOCKET_RETARDER_UNIFORMDIST_B=500
